### ISSUE TITLE
Implement End-to-End Test for Core User Flows

### ISSUE THREAD

**Issue by yasminehilout** [XavierGuertin/WildfireVisualizationProject#104]
**As a developer**, I want to implement an end-to-end (E2E) test for core user flows so that I can validate the application's functionality and user experience from start to finish, ensuring critical workflows are reliable.

- **Size/Points**: L (5)
- **Priority**: High
- **Risk**: Medium (E2E tests can be sensitive to UI changes)
- **Child of Epic**: Frontend UI Development

#### Acceptance Criteria:
- E2E tests should cover key user workflows, such as:
  - Dataset selection and loading on the map
  - Interaction with map navigation tools (zoom, pan, reset)
  - Accessing and updating settings
- Tests should validate the correct display of UI elements and expected responses to user actions.
- E2E tests must run automatically in the CI/CD pipeline, with clear reporting for any failed tests.
- The E2E test framework should allow for easy updates as the application evolves.

**Comment by im-samwong** [comment]
Did some work in iteration 5 #109, pushing to next iteration 6 to cover more user stories.

**Comment by im-samwong** [comment]
Just going to open a new issue considering there will be more user stories making issue larger.

**Comment by LiamDaigle** [comment]
### Understanding the Requirements
This issue was concerned with coming up with the core user flows and testing them end to end to simulate a user.

### Technical Challenges & Backend Integration

- Started by brainstorming the user flows that could be created with the components we had. 
- Added an npm command to easier open up Cypress (the testing tool)
- Fixed config issues
- Came up with e2e testing for loading/collapsing available datasets and metadata.
- Fixed another config issue that was causing our CI/CD pipeline to fail as it was referencing the wrong directory

### Final Thoughts / Engineering Outcome
The end result of this task is an added layer of stability to the application by ensuring that not only do the frontend and backend work in isolation, but they also properly interact with each other. Cypress tests are also very maintainable and easy to understand, allowing us to be able to modify them in the future if anything fails.
